# Number of days of inactivity before an issue becomes stale
daysUntilStale: 90
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - WIP
  - important
  - feature-request
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Thanks for contributing to this issue. As it has been 90 days since the last activity,
  we are automatically closing the issue in 24 hours. This is often because the request
  was already solved in some way and it just wasn't updated or it's no longer applicable.
  If that's not the case, please do feel free to either reopen this issue or open a new
  one. We'll gladly take a look again!
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false

# Limit to only `issues` or `pulls`
only: issues
