language: node_js
node_js:
  - "6"

env:
  global:
    - SAUCE_USERNAME=trickeyone
    - SAUCE_ACCESS_KEY=298cfe3e-8e2d-45a6-a6fb-da53ad523963
    - BROWSER_PROVIDER_READY_FILE=/tmp/sauce-connect-ready
    - LOGS_DIR=/tmp/logs

addons:
  firefox: "latest"
  sause_connect: true

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g gulp

install:
  - npm install

script:
  - gulp ci && npm run api-doc-test
  - gulp saucelabs

sudo: false